apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d0uowcbzb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d0uowcbzb-python 
  name: d0uowcbzb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d0uowcbzb-python 
